backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "source/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "source/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "DOI", name: "doi", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}